In [8]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [9]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [10]:
tf.reset_default_graph()
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [13]:
with tf.variable_scope("one_cell") as scope:
    hidden_size = 2
    cell = tf.nn.rnn_cell.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size,cell.state_size)
    
    x_data = np.array([[h]], dtype = np.float32)
    pp.pprint(x_data)
    outputs,_states = tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 2
array([[[1., 0., 0., 0.]]], dtype=float32)


ValueError: Variable one_cell/RNN/BasicRNNCell/Linear/Matrix already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "<ipython-input-12-08b2e2ff8bb8>", line 8, in <module>
    outputs,_states = tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
  File "/Users/charming/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/charming/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):


In [ ]:
with tf.variable_scope("two_sequences") as scope:
    hidden_size=2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data=np.array([[h,e,l,l,o]],dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs,_states = tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())
    

In [ ]:
with tf.variable_scope("3_batches") as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data = np.array([[h,e,l,l,o],[e,o,l,l,o],[l,l,e,h,l]],dtype = np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs,_states = tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

In [ ]:
with tf.variable_scope("3_batches_dynamic_length") as scope:
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size,state_is_tuple=True)
    outputs,_states = tf.nn.dynamic_rnn(cell,x_data,sequence_length=[5,3,4],
                                       dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

In [ ]:
with tf.variable_scope('initial_state') as scope:
    batch_size = 3
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size,state_is_tuple=True)
    initial_state = cell.zero_state(batch_size,tf.float32)
    outputs,_states = tf.nn.dynamic_rnn(cell,x_data,initial_state=initial_state,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

In [ ]:
batch_size = 3
sequence_length = 5
input_dim = 3

x_data = np.arange(45,dtype=np.float32).reshape(batch_size,sequence_length,input_dim)
pp.pprint(x_data)

In [7]:
tf.reset_default_graph()
with tf.variable_scope("Multi") as scope:
    
    cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=5,state_is_tuple=True)
    cell = tf.nn.rnn_cell.MultiRNNCell([cell] * 3,state_is_tuple=True)
    
    outputs,states = tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    print('dy rnn:',outputs)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

NameError: name 'x_data' is not defined

In [63]:
hidden_size=3
sequence_length=5
batch_size=3
num_classes=5

pp.pprint(x_data) # hidden_size=3, sequence_length=4, batch_size=2
x_data = x_data.reshape(-1, hidden_size)
pp.pprint(x_data)

softmax_w = np.arange(15, dtype=np.float32).reshape(hidden_size, num_classes)
outputs = np.matmul(x_data, softmax_w)
outputs = outputs.reshape(-1, sequence_length, num_classes) # batch, seq, class
pp.pprint(outputs) 

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.],
       [36., 37., 38.],
       [39., 40., 41.],
       [42., 43., 44.]], dtype=float32)
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.],
       [36., 37., 38.],
       [39., 40., 41.],
       [42., 43., 44.]], dtype=float32)
array([[[  25.,   28.,   31.,   34.,   37.],
        [  70.,   82.,   94.,  106.,  118.],
        [ 115.,  136.,  157.,  178.,  199.],
        [ 160.,  190.,  220.,  250.,  280.],
        [ 205.,  244.,  283.,  322.,  361.]],

       [[ 250.,  298.

In [ ]:
y_data = tf.constant([[1, 1, 1]])

# [batch_size, sequence_length, emb_dim ]
prediction = tf.constant([[[0.2, 0.7], [0.6, 0.2], [0.2, 0.9]]], dtype=tf.float32)

# [batch_size * sequence_length]
weights = tf.constant([[1, 1, 1]], dtype=tf.float32)

sequence_loss = tf.contrib.seq2seq.sequence_loss(logits=prediction, targets=y_data, weights=weights)
sess.run(tf.global_variables_initializer())
print("Loss: ", sequence_loss.eval())