In [1]:
import numpy as np

In [3]:
xy = np.loadtxt("data-01-test-score.csv",delimiter=',', dtype=np.float32)

In [16]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [17]:
y_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.],
       [149.],
       [115.],
       [175.],
       [164.],
       [141.],
       [141.],
       [184.],
       [152.],
       [148.],
       [192.],
       [147.],
       [183.],
       [177.],
       [159.],
       [177.],
       [175.],
       [175.],
       [149.],
       [192.]], dtype=float32)

In [18]:
print(x_data.shape,x_data,len(x_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25


In [19]:
print(y_data.shape,y_data)

(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [20]:
import tensorflow as tf

/Users/charming/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [21]:
tf.set_random_seed(777)

In [22]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

In [23]:
W = tf.Variable(tf.random.normal([3,1]),name="weight")
b = tf.Variable(tf.random.normal([1]),name="bias")

In [24]:
hypothesis = tf.matmul(X,W) + b

In [25]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [26]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [27]:
sess = tf.Session()

In [28]:
sess.run(tf.global_variables_initializer())

In [30]:
for i in range(2001):
    cost_val, hy_val,_ = sess.run([cost,hypothesis,train],feed_dict={X : x_data, Y : y_data})
    if i % 10 == 0:
        print(i,"cost is:",cost_val,"hy is",hy_val)

0 cost is: 24.708477 hy is [[154.4279 ]
 [185.55862]
 [182.90576]
 [198.08968]
 [142.52   ]
 [103.55304]
 [146.79262]
 [106.70373]
 [172.1535 ]
 [157.13383]
 [142.5537 ]
 [140.17722]
 [190.04842]
 [159.59692]
 [147.35359]
 [187.26907]
 [153.32832]
 [175.38782]
 [181.36868]
 [162.13152]
 [172.44421]
 [173.06126]
 [164.73447]
 [158.2394 ]
 [192.79105]]
10 cost is: 24.5689 hy is [[154.41759 ]
 [185.55879 ]
 [182.8987  ]
 [198.09114 ]
 [142.51572 ]
 [103.56547 ]
 [146.80379 ]
 [106.725716]
 [172.16777 ]
 [157.16838 ]
 [142.55882 ]
 [140.19133 ]
 [190.03198 ]
 [159.57101 ]
 [147.36769 ]
 [187.27682 ]
 [153.29642 ]
 [175.40408 ]
 [181.34962 ]
 [162.11476 ]
 [172.45589 ]
 [173.06955 ]
 [164.74188 ]
 [158.20767 ]
 [192.78494 ]]
20 cost is: 24.43043 hy is [[154.40733 ]
 [185.55899 ]
 [182.89168 ]
 [198.0926  ]
 [142.51144 ]
 [103.577835]
 [146.81493 ]
 [106.74765 ]
 [172.18196 ]
 [157.20277 ]
 [142.56392 ]
 [140.20537 ]
 [190.01561 ]
 [159.54521 ]
 [147.38176 ]
 [187.28453 ]
 [153.26466 ]
 [175

370 cost is: 20.219183 hy is [[154.0813  ]
 [185.55771 ]
 [182.66483 ]
 [198.14212 ]
 [142.36282 ]
 [103.97151 ]
 [147.1835  ]
 [107.472786]
 [172.63376 ]
 [158.31178 ]
 [142.73082 ]
 [140.65602 ]
 [189.48402 ]
 [158.70491 ]
 [147.8432  ]
 [187.52997 ]
 [152.22528 ]
 [175.95958 ]
 [180.71652 ]
 [161.56018 ]
 [172.85022 ]
 [173.34131 ]
 [164.99652 ]
 [157.15535 ]
 [192.57628 ]]
380 cost is: 20.115232 hy is [[154.07286 ]
 [185.5575  ]
 [182.65887 ]
 [198.1435  ]
 [142.35861 ]
 [103.98172 ]
 [147.19345 ]
 [107.492355]
 [172.64548 ]
 [158.34091 ]
 [142.73529 ]
 [140.6678  ]
 [189.46996 ]
 [158.6826  ]
 [147.85555 ]
 [187.53635 ]
 [152.19756 ]
 [175.97421 ]
 [180.70033 ]
 [161.54605 ]
 [172.86053 ]
 [173.34816 ]
 [165.00323 ]
 [157.12848 ]
 [192.57079 ]]
390 cost is: 20.01209 hy is [[154.0645 ]
 [185.55727]
 [182.65292]
 [198.14485]
 [142.35442]
 [103.99187]
 [147.20337]
 [107.51187]
 [172.6571 ]
 [158.3699 ]
 [142.73972]
 [140.67952]
 [189.45595]
 [158.6604 ]
 [147.86784]
 [187.54266]
 [15

740 cost is: 16.86963 hy is [[153.79852]
 [185.54344]
 [182.46075]
 [198.19098]
 [142.20908]
 [104.31455]
 [147.53195]
 [108.15753]
 [173.0272 ]
 [159.30466]
 [142.8851 ]
 [141.05577]
 [189.00085]
 [157.9369 ]
 [148.2719 ]
 [187.74394]
 [151.26547]
 [176.47372]
 [180.16263]
 [161.07858]
 [173.20912]
 [173.5719 ]
 [165.23373]
 [156.23648]
 [192.3824 ]]
750 cost is: 16.791882 hy is [[153.79166]
 [185.5429 ]
 [182.45569]
 [198.19225]
 [142.205  ]
 [104.3229 ]
 [147.54083]
 [108.17497]
 [173.03679]
 [159.32921]
 [142.88899]
 [141.0656 ]
 [188.98883]
 [157.9177 ]
 [148.28271]
 [187.74916]
 [151.24133]
 [176.48688]
 [180.14888]
 [161.06668]
 [173.21823]
 [173.57755]
 [165.23984]
 [156.21368]
 [192.37744]]
760 cost is: 16.714764 hy is [[153.78484 ]
 [185.54236 ]
 [182.45065 ]
 [198.19351 ]
 [142.20091 ]
 [104.3312  ]
 [147.54968 ]
 [108.192345]
 [173.0463  ]
 [159.35365 ]
 [142.89285 ]
 [141.07538 ]
 [188.97682 ]
 [157.89856 ]
 [148.29349 ]
 [187.75433 ]
 [151.21729 ]
 [176.5     ]
 [180.1351

1150 cost is: 14.129494 hy is [[153.54684]
 [185.51588]
 [182.27086]
 [198.24112]
 [142.04431]
 [104.62163]
 [147.87451]
 [108.82978]
 [173.37918]
 [160.22327]
 [143.03314]
 [141.42157]
 [188.546  ]
 [157.20923]
 [148.68553]
 [187.93561]
 [150.34555]
 [176.98358]
 [179.64574]
 [160.633  ]
 [173.55887]
 [173.77946]
 [165.47058]
 [155.38087]
 [192.18939]]
1160 cost is: 14.072855 hy is [[153.5414 ]
 [185.51506]
 [182.26663]
 [198.24226]
 [142.04036]
 [104.62827]
 [147.88231]
 [108.84513]
 [173.38678]
 [160.24355]
 [143.03645]
 [141.42958]
 [188.53581]
 [157.1929 ]
 [148.69487]
 [187.93974]
 [150.32478]
 [176.99529]
 [179.63423]
 [160.62312]
 [173.56682]
 [173.78395]
 [165.47603]
 [155.36188]
 [192.18494]]
1170 cost is: 14.016714 hy is [[153.53601 ]
 [185.51427 ]
 [182.26245 ]
 [198.24345 ]
 [142.03644 ]
 [104.634895]
 [147.89014 ]
 [108.86045 ]
 [173.39438 ]
 [160.26375 ]
 [143.0398  ]
 [141.43758 ]
 [188.52573 ]
 [157.1767  ]
 [148.70421 ]
 [187.9439  ]
 [150.30414 ]
 [177.00697 ]
 [179.

1540 cost is: 12.213082 hy is [[153.35693 ]
 [185.48131 ]
 [182.11992 ]
 [198.2851  ]
 [141.89406 ]
 [104.85494 ]
 [148.16296 ]
 [109.395164]
 [173.64636 ]
 [160.94862 ]
 [143.15472 ]
 [141.70679 ]
 [188.17976 ]
 [156.61934 ]
 [149.02728 ]
 [188.08134 ]
 [149.59065 ]
 [177.41667 ]
 [179.23361 ]
 [160.28111 ]
 [173.85081 ]
 [173.93816 ]
 [165.67307 ]
 [154.70033 ]
 [192.0248  ]]
1550 cost is: 12.171018 hy is [[153.35265 ]
 [185.48036 ]
 [182.11641 ]
 [198.28621 ]
 [141.89034 ]
 [104.860275]
 [148.16994 ]
 [109.4088  ]
 [173.65248 ]
 [160.96556 ]
 [143.15764 ]
 [141.71342 ]
 [188.17116 ]
 [156.6054  ]
 [149.03548 ]
 [188.0847  ]
 [149.5727  ]
 [177.42719 ]
 [179.22397 ]
 [160.27292 ]
 [173.85786 ]
 [173.94182 ]
 [165.67801 ]
 [154.68443 ]
 [192.02083 ]]
1560 cost is: 12.1292715 hy is [[153.34834 ]
 [185.47937 ]
 [182.11288 ]
 [198.28728 ]
 [141.88657 ]
 [104.865555]
 [148.17686 ]
 [109.42239 ]
 [173.65852 ]
 [160.98239 ]
 [143.16052 ]
 [141.71999 ]
 [188.16255 ]
 [156.59149 ]
 [149.04361

In [34]:
print("your score will be",sess.run(hypothesis, feed_dict={X :[[91,87,70]]}))

your score will be [[166.33817]]


In [35]:
filename_queue = tf.train.string_input_producer(["data-01-test-score.csv"],shuffle=False,name="filename_queue")

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [36]:
reader = tf.TextLineReader()

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [37]:
key, value = reader.read(filename_queue)

In [38]:
record_defaults = [[0.],[0.],[0.],[0.]]

In [40]:
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [43]:
train_x_batch, train_y_batch = \
tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [44]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [45]:
W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name="weight")

In [48]:
hypo = tf.matmul(X,W) + b

In [49]:
cost = tf.reduce_mean(tf.square(hypo - Y))

In [50]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [51]:
sess = tf.Session()

In [54]:
sess.run(tf.global_variables_initializer())

In [55]:
coord = tf.train.Coordinator()

In [56]:
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [57]:
for i in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val,_ = sess.run([cost,hypo,train],feed_dict = {X : x_batch, Y : y_batch})
    if i % 10 == 0:
        print(i,"cost :", cost_val,"hy :",hy_val)

0 cost : 57347.73 hy : [[ -97.77742 ]
 [-104.20064 ]
 [ -46.811993]
 [ -58.171352]
 [ -67.761246]
 [ -68.14546 ]
 [ -78.468834]
 [ -91.865166]
 [-108.81543 ]
 [ -93.95625 ]]
10 cost : 58.309242 hy : [[183.11322]
 [179.1309 ]
 [143.5791 ]
 [149.48022]
 [179.11435]
 [144.73416]
 [151.66766]
 [192.32619]
 [137.95529]
 [176.85745]]
20 cost : 64.53941 hy : [[185.01398]
 [180.85973]
 [145.18419]
 [151.03362]
 [181.25705]
 [146.52888]
 [153.33603]
 [194.41377]
 [139.66188]
 [178.86736]]
30 cost : 64.07517 hy : [[184.98163]
 [180.7981 ]
 [145.1886 ]
 [151.00867]
 [181.29414]
 [146.57321]
 [153.33539]
 [194.40242]
 [139.70139]
 [178.8835 ]]
40 cost : 63.5472 hy : [[184.93633]
 [180.7246 ]
 [145.18213]
 [150.97313]
 [181.3168 ]
 [146.60544]
 [153.32346]
 [194.37688]
 [139.72939]
 [178.88606]]
50 cost : 63.023293 hy : [[184.89108]
 [180.65132]
 [145.17561]
 [150.93767]
 [181.33922]
 [146.63744]
 [153.31148]
 [194.35132]
 [139.75717]
 [178.88855]]
60 cost : 62.504223 hy : [[184.84607]
 [180.57838]

530 cost : 42.72097 hy : [[182.93602]
 [177.4961 ]
 [144.89835]
 [149.40778]
 [182.30006]
 [148.00392]
 [152.8069 ]
 [193.24715]
 [140.93263]
 [179.01704]]
540 cost : 42.38473 hy : [[182.89946]
 [177.43735]
 [144.89326]
 [149.37924]
 [182.31786]
 [148.02913]
 [152.79774]
 [193.22652]
 [140.9541 ]
 [179.01988]]
550 cost : 42.05142 hy : [[182.86304]
 [177.37886]
 [144.88818]
 [149.35081]
 [182.33554]
 [148.05421]
 [152.7886 ]
 [193.20593]
 [140.97543]
 [179.02272]]
560 cost : 41.721165 hy : [[182.8268 ]
 [177.32063]
 [144.88313]
 [149.32253]
 [182.35315]
 [148.07918]
 [152.77953]
 [193.18547]
 [140.99666]
 [179.02556]]
570 cost : 41.393875 hy : [[182.79071]
 [177.26268]
 [144.87811]
 [149.29436]
 [182.37068]
 [148.10402]
 [152.77051]
 [193.16512]
 [141.01779]
 [179.02843]]
580 cost : 41.069534 hy : [[182.75478]
 [177.20497]
 [144.87312]
 [149.26633]
 [182.38812]
 [148.12875]
 [152.76154]
 [193.1448 ]
 [141.03879]
 [179.03128]]
590 cost : 40.7481 hy : [[182.719  ]
 [177.14754]
 [144.86815

1140 cost : 26.874811 hy : [[180.9708 ]
 [174.35521]
 [144.63014]
 [147.8783 ]
 [183.24342]
 [149.33667]
 [152.33072]
 [192.13773]
 [142.05219]
 [179.19766]]
1150 cost : 26.680807 hy : [[180.94267]
 [174.31056]
 [144.62639]
 [147.85649]
 [183.2567 ]
 [149.35535]
 [152.32417]
 [192.12184]
 [142.06764]
 [179.2007 ]]
1160 cost : 26.488586 hy : [[180.91469]
 [174.26611]
 [144.62267]
 [147.83478]
 [183.26991]
 [149.37395]
 [152.31769]
 [192.10605]
 [142.083  ]
 [179.20375]]
1170 cost : 26.298038 hy : [[180.88683]
 [174.22185]
 [144.61897]
 [147.81317]
 [183.2831 ]
 [149.39247]
 [152.31123]
 [192.09033]
 [142.09828]
 [179.2068 ]]
1180 cost : 26.109186 hy : [[180.85905]
 [174.1778 ]
 [144.61528]
 [147.79164]
 [183.29619]
 [149.41087]
 [152.30481]
 [192.07466]
 [142.11348]
 [179.20985]]
1190 cost : 25.922039 hy : [[180.8314 ]
 [174.13394]
 [144.6116 ]
 [147.77022]
 [183.3092 ]
 [149.4292 ]
 [152.29842]
 [192.05905]
 [142.1286 ]
 [179.21289]]
1200 cost : 25.736668 hy : [[180.80391]
 [174.0903 ]

1730 cost : 17.95408 hy : [[179.50212]
 [172.03586]
 [144.4392 ]
 [146.74286]
 [183.92798]
 [150.29558]
 [152.00293]
 [191.30907]
 [142.8326 ]
 [179.37924]]
1740 cost : 17.839998 hy : [[179.4803 ]
 [172.00162]
 [144.43645]
 [146.72604]
 [183.93802]
 [150.30954]
 [151.99829]
 [191.29675]
 [142.84375]
 [179.38234]]
1750 cost : 17.726864 hy : [[179.45854]
 [171.9675 ]
 [144.43369]
 [146.70929]
 [183.94797]
 [150.32343]
 [151.99368]
 [191.28448]
 [142.85481]
 [179.38542]]
1760 cost : 17.61479 hy : [[179.43689]
 [171.93355]
 [144.43097]
 [146.69261]
 [183.95789]
 [150.33723]
 [151.98909]
 [191.27228]
 [142.86583]
 [179.38849]]
1770 cost : 17.503696 hy : [[179.41533]
 [171.89975]
 [144.42824]
 [146.67601]
 [183.96774]
 [150.35098]
 [151.98453]
 [191.2601 ]
 [142.87679]
 [179.39157]]
1780 cost : 17.393557 hy : [[179.39386]
 [171.86609]
 [144.42554]
 [146.65947]
 [183.97757]
 [150.36465]
 [151.97998]
 [191.248  ]
 [142.88768]
 [179.39465]]
1790 cost : 17.284464 hy : [[179.37248]
 [171.8326 ]
 

In [58]:
coord.request_stop()

In [59]:
coord.join(threads)