In [1]:
import tensorflow as tf
import numpy as np

/Users/charming/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
t = np.array([0,1,2,3,4,5,6])

In [5]:
print(t.ndim)

1


In [6]:
print(t.shape)

(7,)


In [7]:
print(t[0])

0


In [8]:
t[2:-1]

array([2, 3, 4, 5])

In [9]:
t[-1]

6

In [10]:
t[:2]

array([0, 1])

In [12]:
t[:-1]

array([0, 1, 2, 3, 4, 5])

In [16]:
tt = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])

In [17]:
print(tt)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [19]:
print(tt.ndim)
print(tt.shape)

2
(4, 3)


In [40]:
t = tf.constant([[1,2],
                 [3,4]])

In [44]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print(tf.shape(t))

Tensor("Shape_16:0", shape=(2,), dtype=int32)


In [43]:
tf.shape(t).eval(session=sess)

RuntimeError: Attempted to use a closed Session.

In [49]:
a = tf.constant([1,2])

In [56]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))

[1 2]


In [59]:
with tf.Session():
    print(tf.shape(t).eval())

[2 2]


In [60]:
tf.shape(t).eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [83]:
mat1 = tf.constant([[1.,2.],[3.,4.]])
mat2 = tf.constant([[1.],[3.]])

In [84]:
print("mat1 shape : ",mat1.shape)
print("mat2 shape : ",mat2.shape)

mat1 shape :  (2, 2)
mat2 shape :  (2, 1)


In [87]:
with tf.Session():
  
    
    print((mat1+mat2).eval())

[[2. 3.]
 [6. 7.]]


In [102]:
x = [[0.,1.,2.],
     [2.,1.,0.]]

In [108]:
with tf.Session(): 
    a=tf.reshape(x,shape=[-1,3]).eval()
    print(a)

[[0. 1. 2.]
 [2. 1. 0.]]


In [105]:
with tf.Session(): 
    print(tf.argmax(x,axis=1).eval())

[2 0]


In [81]:
mat1*mat2

<tf.Tensor 'mul_1:0' shape=(2, 2) dtype=float32>